### ISSUE TITLE
Drain script failed for rep windows in windows cell deployment

### ISSUE THREAD

**Issue by cfmagnum** [pivotal-cf-experimental/garden-windows-bosh-release#2]
While trying to deploy windows cell as a bosh release , our deployment fails with the following error:

`   Failed updating instance cell_windows_z1 > cell_windows_z1/5756f2ec-0f2f-430f-af0a-edfdfe9b295b (0) (canary): Action Failed get_tas
k: Task 334f5a83-225c-4164-7b11-3ddcd7a51806 result: 1 of 1 drain scripts failed. Failed Jobs: rep_windows. (00:00:01)
   Failed updating instance cell_windows_z2 > cell_windows_z2/bc674720-3f9c-4602-829b-8c17fa02c5a1 (0) (canary): Action Failed get_tas
k: Task 48fa5ec0-3642-45c7-5ba7-a9975e79961d result: 1 of 1 drain scripts failed. Failed Jobs: rep_windows. (00:00:01)

Error 450001: Action Failed get_task: Task 334f5a83-225c-4164-7b11-3ddcd7a51806 result: 1 of 1 drain scripts failed. Failed Jobs: rep_
windows.
`
We are currently using cf v254 and diego v1.10.1 , garden windows release v0.3.0 , windows stemcell= bosh-aws-xen-hvm-windows-stemcell-go_agent  | windows2012R2                               | 0.0.50*  | ami-b61b56a1 light

**Comment by sunjayBhatia** [comment]
@cfmagnum The rep_windows job is not actually part of this BOSH release, it is part of diego-release. It might be more helpful to take this issue and the logs from the rep_windows job to the diego-release repo, as the maintainers of that code would know more about the rep drain process and so we can keep the question/answer/learnings in the right place.

We are of course happy to help and will likely be commenting over in that repo/issue as well.

**Comment by cfmagnum** [comment]
Thanks Sunjay. Will raise it in the diego-release repository!
